### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dessant** [kivy-garden/garden.moretransitions#3]
Garden repositories must be released under the MIT license. Please tell us if you agree to release it with this license, or simply add the file, following this template: https://github.com/kivy-garden/kivy-garden.github.io/blob/master/LICENSE.

**Comment by remip** [comment]
Hi,

I don't have any objection, you can add the licence.

Regards,
Rémi

2015-11-09 18:37 GMT+01:00 dessant <notifications@github.com>:

> Garden repositories must be released under the MIT license. Please tell us
> if you agree to release it with this license, or simply add the file,
> following this template:
> https://github.com/kivy-garden/kivy-garden.github.io/blob/master/LICENSE.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kivy-garden/garden.moretransitions/issues/3>.
>



-- 
Rémi

**Comment by dessant** [comment]
@remip, thanks, I have added the license file.
